// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh5a5TljPdjJ7Xen7SjaU7-dQyyLbWVbg',
    appId: '1:1021062469377:web:c740b75891aab12207ad00',
    messagingSenderId: '1021062469377',
    projectId: 'mynotes-cd6ac',
    authDomain: 'mynotes-cd6ac.firebaseapp.com',
    storageBucket: 'mynotes-cd6ac.appspot.com',
    measurementId: 'G-2096KX3HV6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsq99dBW8xc3gc0K1rn1_hrye-qWNNTi4',
    appId: '1:1021062469377:android:c9835afe15b407c307ad00',
    messagingSenderId: '1021062469377',
    projectId: 'mynotes-cd6ac',
    storageBucket: 'mynotes-cd6ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6Y148E3vdoXeD0jvsgzOz0LNg6nE-04',
    appId: '1:1021062469377:ios:57966c5147e1725907ad00',
    messagingSenderId: '1021062469377',
    projectId: 'mynotes-cd6ac',
    storageBucket: 'mynotes-cd6ac.appspot.com',
    iosClientId:
        '1021062469377-rev4je81gr8thkg6gk1242tjq2rmoeu3.apps.googleusercontent.com',
    iosBundleId: 'com.tasbe7na.mynotes',
  );
}
